/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddImage: typeof import('./components/icons/AddImage.vue')['default']
    ImageUpload: typeof import('./components/ImageUpload.vue')['default']
  }
}
