/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddImage: typeof import('./components/icons/AddImage.vue')['default']
    ArrowRight: typeof import('./components/icons/ArrowRight.vue')['default']
    Copy: typeof import('./components/icons/Copy.vue')['default']
    Download: typeof import('./components/icons/Download.vue')['default']
    ImageList: typeof import('./components/ImageList.vue')['default']
    ImageUpload: typeof import('./components/ImageUpload.vue')['default']
    Plus: typeof import('./components/icons/Plus.vue')['default']
    TheHeading: typeof import('./components/TheHeading.vue')['default']
    Trash: typeof import('./components/icons/Trash.vue')['default']
  }
}
